"""refresh database

Revision ID: 3c6feecb568a
Revises: 
Create Date: 2026-05-29 13:39:35.737648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c6feecb568a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analytics_id'), table_name='analytics')
    op.drop_table('analytics')
    op.alter_column('comments', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_index(op.f('idx_comments_music_id'), table_name='comments')
    op.drop_index(op.f('idx_comments_news_id'), table_name='comments')
    op.drop_index(op.f('idx_comments_video_id'), table_name='comments')
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_foreign_key(None, 'comments', 'music', ['music_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'news', ['news_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'videos', ['video_id'], ['id'])
    op.drop_column('music', 'cloudinary_id')
    op.drop_column('music', 'cover_public_id')
    op.create_unique_constraint(None, 'news', ['image_hash'])
    op.drop_column('videos', 'cloudinary_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('cloudinary_id', sa.VARCHAR(length=500), nullable=True))
    op.drop_constraint(None, 'news', type_='unique')
    op.add_column('music', sa.Column('cover_public_id', sa.VARCHAR(length=255), nullable=True))
    op.add_column('music', sa.Column('cloudinary_id', sa.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.create_index(op.f('idx_comments_video_id'), 'comments', ['video_id'], unique=False)
    op.create_index(op.f('idx_comments_news_id'), 'comments', ['news_id'], unique=False)
    op.create_index(op.f('idx_comments_music_id'), 'comments', ['music_id'], unique=False)
    op.alter_column('comments', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_table('analytics',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('page', sa.VARCHAR(length=255), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=255), nullable=True),
    sa.Column('user_agent', sa.TEXT(), nullable=True),
    sa.Column('visits', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_id'), 'analytics', ['id'], unique=False)
    # ### end Alembic commands ###
